name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [  '1.20' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: |
          go version
          pwd
          ls -ltr
          cd src
          ls -ltr
          cd greetings
          go mod init example.com/greetings
          cd ../hello 
          go mod init example.com/hello
          go mod edit -replace example.com/greetings=../greetings  
          go mod tidy
          go run . 
